language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_install:
  - pecl install xdebug
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - ant composer-init
  - ant build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml
